webtalk_init -webtalk_dir D:/COA_LAB/Final Assignments/RISC_Customized_ALU_Submission/Reg_Bank_and_ALU_Lab_Submission.sim/sim_1/behav/xsim/xsim.dir/ALU_NOR_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Oct  1 16:21:16 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2960000" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211289124_1777522482_210647771_627" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b826620f-dda8-42c1-8d7f-1fc1885ccfd0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "457b98182d5a4de99ca18990b40da8a5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3292 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6772_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4148318848 -regid "211289124_1777522482_210647771_627" -xml D:/COA_LAB/Final Assignments/RISC_Customized_ALU_Submission/Reg_Bank_and_ALU_Lab_Submission.sim/sim_1/behav/xsim/xsim.dir/ALU_NOR_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/COA_LAB/Final Assignments/RISC_Customized_ALU_Submission/Reg_Bank_and_ALU_Lab_Submission.sim/sim_1/behav/xsim/xsim.dir/ALU_NOR_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/COA_LAB/Final Assignments/RISC_Customized_ALU_Submission/Reg_Bank_and_ALU_Lab_Submission.sim/sim_1/behav/xsim/xsim.dir/ALU_NOR_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
